Repository Kodeworks/liquidator-backend, pull requests merged in 2019-06, with the labels that each got.

#2 Add a custom user model and company model.
  company/__init__.py
  company/admin.py
  company/apps.py
  company/migrations/0001_initial.py
  company/migrations/__init__.py
  company/models.py
  company/tests.py
  company/views.py
  custom_auth/__init__.py
  custom_auth/admin.py
  custom_auth/apps.py
  custom_auth/migrations/0001_initial.py
  custom_auth/migrations/__init__.py
  custom_auth/models.py
  custom_auth/tests.py
  custom_auth/views.py
  liquidator/settings.py
Labels: feature

#18 Feature/jwt token
  .circleci/config.yml
  Makefile
  custom_auth/serializers.py
  custom_auth/tests.py
  custom_auth/urls.py
  custom_auth/views.py
  liquidator/settings.py
  liquidator/urls.py
  requirements.txt
Labels: feature

#19 Add User and Company API
  company/migrations/0002_auto_20190621_0935.py
  company/models.py
  company/serializers.py
  company/urls.py
  company/views.py
  custom_auth/admin.py
  custom_auth/migrations/0002_auto_20190621_0935.py
  custom_auth/models.py
  custom_auth/roles.py
  custom_auth/serializers.py
  custom_auth/tests.py
  custom_auth/views.py
  liquidator/urls.py
Labels: feature

#22 Update README
  README.md
Labels: fix

#23 Fix code style
  .pep8speaks.yml
  Makefile
  company/urls.py
  custom_auth/models.py
  custom_auth/roles.py
  custom_auth/tests.py
  custom_auth/urls.py
  custom_auth/views.py
  requirements.txt
  setup.cfg
Labels: fix

#24 Add models for recurring transaction and transaction template.
  transaction/migrations/0002_auto_20190621_1657.py
  transaction/models.py
Labels: feature

#28 Support requests from localhost:3000 with CORS
  liquidator/settings.py
  requirements.txt
Labels: bug

#29 Return JWT tokens when creating an user
  custom_auth/tests.py
  custom_auth/views.py
Labels: fix

#31 Fix user and company logic, and add tests
  company/admin.py
  company/migrations/0003_auto_20190625_1501.py
  company/models.py
  company/serializers.py
  company/tests.py
  company/views.py
  custom_auth/models.py
  custom_auth/roles.py
  custom_auth/tests.py
  custom_auth/views.py
Labels: fix

#32 Improve admin site for user and company
  company/admin.py
  custom_auth/admin.py
  custom_auth/models.py
Labels: fix

#35 Set up pagination
  liquidator/settings.py
  liquidator/urls.py
  transaction/admin.py
  transaction/migrations/0003_auto_20190625_1045.py
  transaction/migrations/0004_auto_20190625_1510.py
  transaction/models.py
  transaction/serializers.py
  transaction/tests.py
  transaction/urls.py
  transaction/views.py
Labels: feature

#34 Add BankBalance model, serializer and tests
  balance/__init__.py
  balance/admin.py
  balance/apps.py
  balance/migrations/0001_initial.py
  balance/migrations/0002_auto_20190627_1503.py
  balance/migrations/__init__.py
  balance/models.py
  balance/serializers.py
  balance/tests.py
  balance/views.py
  liquidator/settings.py
Labels: feature

#36 Restructure and generalize views and tests
  base/__init__.py
  base/admin.py
  base/apps.py
  base/migrations/__init__.py
  base/mixins.py
  base/models.py
  base/tests.py
  base/views.py
  company/tests.py
  company/views.py
  custom_auth/tests.py
  custom_auth/views.py
  liquidator/settings.py
  transaction/tests.py
  transaction/views.py
Labels: fix
